import type { INodeProperties } from 'n8n-workflow';

export const providerFields: INodeProperties[] = [
	{
		displayName: 'Provider',
		name: 'provider',
		type: 'options',
		noDataExpression: true,
		options: [
			{ name: 'OpenAI', value: 'openai' },
			{ name: 'Anthropic', value: 'anthropic' },
			{ name: 'Azure OpenAI', value: 'azureOpenai' },
			{ name: 'AWS Bedrock', value: 'bedrock' },
			{ name: 'Databricks', value: 'databricks' },
		],
		default: 'openai',
		description: 'The LLM provider to route through Pay-i',
	},
	{
		displayName: 'Model Provider API Key',
		name: 'providerApiKey',
		type: 'string',
		typeOptions: { password: true },
		default: '',
		required: true,
		description: 'API key or access token for the selected provider',
		displayOptions: { hide: { provider: ['databricks'] } },
	},
	{
		displayName: 'Model ID',
		name: 'model',
		type: 'string',
		default: 'gpt-4o',
		required: true,
		placeholder: 'e.g. gpt-4o, claude-sonnet-4-20250514',
		description: 'The model ID to use',
		displayOptions: { hide: { provider: ['databricks'] } },
	},
	// Azure extras
	{
		displayName: 'Azure Deployment Name',
		name: 'azureDeploymentName',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'e.g. my-gpt-4o-deployment',
		displayOptions: { show: { provider: ['azureOpenai'] } },
	},
	{
		displayName: 'Azure API Version',
		name: 'azureApiVersion',
		type: 'string',
		default: '2024-02-01',
		displayOptions: { show: { provider: ['azureOpenai'] } },
	},
	// Bedrock extras
	{
		displayName: 'AWS Secret Access Key',
		name: 'bedrockSecretKey',
		type: 'string',
		typeOptions: { password: true },
		default: '',
		required: true,
		displayOptions: { show: { provider: ['bedrock'] } },
	},
	{
		displayName: 'AWS Session Token',
		name: 'bedrockSessionToken',
		type: 'string',
		typeOptions: { password: true },
		default: '',
		description: 'Optional — for temporary AWS credentials',
		displayOptions: { show: { provider: ['bedrock'] } },
	},
	{
		displayName: 'AWS Region',
		name: 'bedrockRegion',
		type: 'string',
		default: 'us-east-1',
		displayOptions: { show: { provider: ['bedrock'] } },
	},
	// Databricks extras (workspace URL + PAT come from the Databricks API credential)
	{
		displayName: 'Serving Endpoint Name (Model)',
		name: 'databricksEndpointName',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'e.g. databricks-meta-llama-3-3-70b-instruct, databricks-gpt-5-4',
		description:
			'The name of the Databricks Model Serving endpoint. Sent as the "model" field in the request body — Databricks routes the request internally based on this value. The proxy URL is always /serving-endpoints/chat/completions; the endpoint name does NOT appear in the URL. Endpoint must accept OpenAI-shape chat/completions requests (foundation models do; custom MLflow / tensor models do NOT — Body Format support for those is on the 0.4.0 roadmap).',
		displayOptions: { show: { provider: ['databricks'] } },
	},
	{
		displayName: 'Price-As Resource (Optional)',
		name: 'databricksPriceAsResource',
		type: 'string',
		default: '',
		placeholder: 'e.g. databricks-gpt-5-4 (leave empty for foundation models)',
		description:
			'Sent as the xProxy-PriceAs-Resource HEADER (does not change routing — only Pay-i\'s cost-tracking lookup). Leave empty when the Serving Endpoint Name already matches a known Databricks foundation model registered in Pay-i\'s pricing tables. Set this when your endpoint is a custom wrapper around a foundation model (e.g. endpoint name "payi-devorg" but the underlying model is "databricks-gpt-5-4") so Pay-i resolves per-model pricing instead of marking the call as an unknown resource. This field is metadata only — it does NOT affect which endpoint Databricks invokes.',
		displayOptions: { show: { provider: ['databricks'] } },
	},
	{
		displayName: 'Cloud Provider',
		name: 'databricksCloudProvider',
		type: 'options',
		noDataExpression: true,
		options: [
			{ name: 'AWS', value: 'aws' },
			{ name: 'Azure', value: 'azure' },
			{ name: 'Google Cloud (GCP)', value: 'google' },
			{ name: 'Databricks', value: 'databricks' },
		],
		default: 'aws',
		required: true,
		description: 'The cloud provider where your Databricks workspace is hosted (used for cost pricing). Choose Databricks for self-hosted, on-premises, or non-major-cloud deployments using cloud.databricks.com URLs.',
		displayOptions: { show: { provider: ['databricks'] } },
	},
];
